# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predictClassForPoint <- function(pointsData, x, y, k) {
    .Call('_ProjAlgoKNN_predictClassForPoint', PACKAGE = 'ProjAlgoKNN', pointsData, x, y, k)
}

knnRcpp <- function(trainingSet, x, y, k) {
    .Call('_ProjAlgoKNN_knnRcpp', PACKAGE = 'ProjAlgoKNN', trainingSet, x, y, k)
}

